//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingsDblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        public long Identifiant { get; set; }
        public long IdentifiantTypesContrat { get; set; }
        public long IdentifiantMetier { get; set; }
        public long IdentifiantClients { get; set; }
        public string Intitule { get; set; }
        public string Reference { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfil { get; set; }
        public string Localisation { get; set; }
        public string NombreDePostes { get; set; }
        public System.DateTime DateDebutPublication { get; set; }
        public int DureeDeDiffusion { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual TypesDeContrat TypesDeContrat { get; set; }
    }
}
